export const GET_ALL_PROJECTS_REQUEST = 'projects/GET_ALL_PROJECTS_REQUEST';
export const GET_ALL_PROJECTS_SUCCESS = 'projects/GET_ALL_PROJECTS_SUCCESS';
export const GET_ALL_PROJECTS_ERROR = 'projects/GET_ALL_PROJECTS_ERROR';

export const CREATE_PROJECT_REQUEST = 'projects/CREATE_PROJECT_REQUEST';
export const CREATE_PROJECT_SUCCESS = 'projects/CREATE_PROJECT_SUCCESS';
export const CREATE_PROJECT_ERROR = 'projects/CREATE_PROJECT_ERROR';
